// "Wusstest du?"-Fakten. Neue Fakten bitte nur UNTEN anhängen –
// die App merkt sich die gezeigten Fakten über ihre Position in der Liste.
const FACTS = [
  // 🌍 Länder, Städte & Einwohner
  'Deutschland hat rund 83 Millionen Einwohner.',
  'Die Hauptstadt von Frankreich ist Paris. In der Stadt selbst leben etwa 2,1 Millionen Menschen, im ganzen Großraum rund 12 Millionen.',
  'Berlin ist die größte Stadt Deutschlands – dort leben rund 3,8 Millionen Menschen.',
  'Hamburg ist die zweitgrößte Stadt Deutschlands mit etwa 1,9 Millionen Einwohnern.',
  'Deutschland besteht aus 16 Bundesländern.',
  'Deutschland hat 9 Nachbarländer: Dänemark, Polen, Tschechien, Österreich, die Schweiz, Frankreich, Luxemburg, Belgien und die Niederlande.',
  'Die Hauptstadt von Italien ist Rom. Dort leben rund 2,8 Millionen Menschen.',
  'Die Hauptstadt von Spanien ist Madrid mit rund 3,3 Millionen Einwohnern.',
  'Die Hauptstadt von Österreich ist Wien. Dort leben rund 2 Millionen Menschen.',
  'Die Hauptstadt der Schweiz ist Bern – die größte Stadt der Schweiz ist aber Zürich.',
  'Die Hauptstadt von Großbritannien ist London mit rund 9 Millionen Einwohnern.',
  'Im Großraum Tokio (Japan) leben rund 37 Millionen Menschen – so viele wie in keiner anderen Stadtregion der Welt.',
  'Die Hauptstadt der USA ist Washington, D.C. – nicht New York!',
  'Die Hauptstadt von Australien ist Canberra – nicht Sydney!',
  'Die Hauptstadt von Kanada ist Ottawa.',
  'Auf der Erde leben rund 8,2 Milliarden Menschen.',
  'Indien ist das Land mit den meisten Einwohnern: über 1,4 Milliarden Menschen.',
  'Russland ist das größte Land der Welt – fast 48-mal so groß wie Deutschland.',
  'Der Vatikan ist das kleinste Land der Welt. Er ist nur etwa 0,44 km² groß – kleiner als viele Stadtparks.',
  'Es gibt rund 195 Länder auf der Welt.',
  'Es gibt 7 Kontinente: Afrika, Antarktika, Asien, Australien, Europa, Nordamerika und Südamerika.',
  'Die Schweiz hat vier Amtssprachen: Deutsch, Französisch, Italienisch und Rätoromanisch.',
  'Frankreich ist das Land, das jedes Jahr von den meisten Touristen der Welt besucht wird.',
  'In Neuseeland leben mehr Schafe als Menschen – etwa viermal so viele.',
  'In Australien gibt es mehr Kängurus als Menschen.',
  'Japan besteht aus über 14.000 Inseln.',
  'Kanada hat die längste Küste aller Länder der Welt.',
  'Venedig ist auf über 100 kleinen Inseln gebaut und hat rund 400 Brücken.',
  'Ganz im Norden von Norwegen geht die Sonne im Sommer wochenlang nicht unter. Das nennt man Mitternachtssonne.',
  'Der Bodensee grenzt an drei Länder: Deutschland, Österreich und die Schweiz.',
  'An Deutschlands Küsten liegen zwei Meere: die Nordsee und die Ostsee.',

  // 🏔️ Natur & Erde
  'Die Zugspitze ist mit 2.962 Metern der höchste Berg Deutschlands.',
  'Der höchste Berg der Welt ist der Mount Everest mit 8.849 Metern.',
  'Der Rhein ist der längste Fluss in Deutschland – rund 865 Kilometer davon fließen durch Deutschland.',
  'Der Rhein fließt durch sechs Länder: Schweiz, Liechtenstein, Österreich, Deutschland, Frankreich und die Niederlande.',
  'Die Donau fließt durch zehn Länder – mehr als jeder andere Fluss der Welt.',
  'Der Nil ist mit rund 6.650 Kilometern einer der beiden längsten Flüsse der Welt. Manche Forscher meinen, der Amazonas ist noch etwas länger.',
  'Der Amazonas-Regenwald in Südamerika ist der größte Regenwald der Welt.',
  'Die Sahara ist die größte heiße Wüste der Welt – fast so groß wie die USA.',
  'Die Antarktis zählt als größte Wüste der Welt, weil dort fast kein Niederschlag fällt.',
  'Der Pazifik ist der größte Ozean. Er ist größer als alle Landflächen der Erde zusammen.',
  'Der Marianengraben im Pazifik ist fast 11.000 Meter tief – der Mount Everest würde komplett darin verschwinden.',
  'Das Tote Meer ist so salzig, dass man darin nicht untergehen kann.',
  'Im Erdkern ist es etwa 5.500 °C heiß – ungefähr so heiß wie an der Oberfläche der Sonne.',
  'Ein Blitz ist rund 30.000 °C heiß – etwa fünfmal heißer als die Oberfläche der Sonne.',
  'Auf der ganzen Erde blitzt es etwa 40- bis 50-mal pro Sekunde.',
  'Zählst du die Sekunden zwischen Blitz und Donner und teilst sie durch 3, weißt du ungefähr, wie viele Kilometer das Gewitter entfernt ist.',
  'Schneeflocken haben fast immer sechs Arme – aber keine gleicht genau der anderen.',
  'Ein Regenbogen entsteht, wenn Sonnenlicht in Regentropfen gebrochen wird.',
  'Die Luft besteht zu etwa 78 % aus Stickstoff und nur zu etwa 21 % aus Sauerstoff.',
  'Auf Meereshöhe kocht Wasser bei 100 °C – auf der Zugspitze schon bei etwa 90 °C.',
  'Schall ist im Wasser etwa viermal so schnell wie in der Luft.',
  'Diamanten bestehen aus Kohlenstoff – genau wie die Mine in deinem Bleistift.',
  'Bambus kann an einem einzigen Tag fast einen Meter wachsen.',
  'Einer der ältesten Bäume der Welt ist eine Kiefer in Kalifornien – sie ist fast 5.000 Jahre alt.',

  // 🚀 Weltall
  'In die Sonne würden etwa 1,3 Millionen Erden hineinpassen.',
  'Das Licht der Sonne braucht ungefähr 8 Minuten, bis es bei uns auf der Erde ankommt.',
  'Der Mond ist etwa 384.000 Kilometer von der Erde entfernt.',
  'Der Mond entfernt sich jedes Jahr etwa 3,8 Zentimeter von der Erde.',
  '1969 betraten Neil Armstrong und Buzz Aldrin als erste Menschen den Mond.',
  'Die Fußabdrücke der Astronauten sind noch heute auf dem Mond – dort gibt es keinen Wind, der sie verweht.',
  'Unser Sonnensystem hat 8 Planeten. Pluto zählt seit 2006 nur noch als Zwergplanet.',
  'Jupiter ist der größte Planet unseres Sonnensystems – über 1.300 Erden würden hineinpassen.',
  'Saturn hat über 270 bekannte Monde – mehr als jeder andere Planet.',
  'Ein Tag auf der Venus dauert länger als ein ganzes Jahr auf der Venus.',
  'Auf dem Mars steht der höchste Vulkan im Sonnensystem: Olympus Mons ist etwa 22 Kilometer hoch.',
  'Die Raumstation ISS fliegt etwa alle 90 Minuten einmal um die Erde.',
  'Im Weltall ist es völlig still, weil es dort keine Luft gibt, die den Schall weiterträgt.',
  'Die Erde braucht rund 365 Tage für eine Runde um die Sonne – das ist ein Jahr.',

  // 🐾 Tiere
  'Der Blauwal ist das größte Tier, das je gelebt hat – bis zu 30 Meter lang.',
  'Das Herz eines Blauwals wiegt etwa 180 Kilogramm.',
  'Der Gepard ist das schnellste Landtier – er schafft rund 100 km/h.',
  'Der Wanderfalke ist das schnellste Tier der Welt: Im Sturzflug erreicht er über 300 km/h.',
  'Oktopusse haben drei Herzen und blaues Blut.',
  'Eine Giraffe hat genauso viele Halswirbel wie ein Mensch: sieben.',
  'Faultiere kommen nur etwa einmal pro Woche vom Baum herunter – um aufs Klo zu gehen.',
  'Pinguine leben fast nur auf der Südhalbkugel der Erde.',
  'Flamingos sind rosa, weil sie kleine Krebse und Algen fressen.',
  'Elefanten können nicht springen.',
  'Ein afrikanischer Elefant kann bis zu 6 Tonnen wiegen – so viel wie etwa vier Autos.',
  'Kolibris sind die einzigen Vögel, die rückwärts fliegen können.',
  'Delfine schlafen immer nur mit einer Gehirnhälfte – die andere bleibt wach.',
  'Katzen schlafen etwa 12 bis 16 Stunden am Tag.',
  'Koalas schlafen bis zu 20 Stunden am Tag.',
  'Hunde können viele tausend Mal besser riechen als Menschen.',
  'Haie gibt es schon seit über 400 Millionen Jahren – also schon lange vor den Dinosauriern.',
  'Seesterne haben kein Gehirn.',
  'Ein Strauß hat größere Augen als sein Gehirn.',
  'Schmetterlinge schmecken mit ihren Füßen.',
  'Jedes Zebra hat ein einzigartiges Streifenmuster – wie ein Fingerabdruck.',
  'Eisbären haben eigentlich schwarze Haut, und ihre Fellhaare sind durchsichtig.',
  'Ameisen können ein Vielfaches ihres eigenen Körpergewichts tragen.',
  'Der Tyrannosaurus rex lebte zeitlich näher an uns Menschen als am Stegosaurus.',
  'Wombats machen würfelförmige Häufchen.',
  'Seeotter halten sich beim Schlafen oft an den Pfoten, damit sie nicht auseinandertreiben.',
  'Krokodile können ihre Zunge nicht herausstrecken.',
  'Der Axolotl kann verlorene Beine einfach nachwachsen lassen.',
  'Eulen können ihren Kopf um bis zu 270 Grad drehen.',
  'Pferde können im Stehen schlafen.',
  'Für ein Glas Honig müssen Bienen Nektar aus mehreren Millionen Blüten sammeln.',

  // 🫀 Menschlicher Körper
  'Ein Erwachsener hat 206 Knochen – ein Baby hat bei der Geburt rund 300.',
  'Der kleinste Knochen im Körper ist der Steigbügel im Ohr – nur etwa 3 Millimeter groß.',
  'Dein Herz schlägt ungefähr 100.000-mal am Tag.',
  'Menschen blinzeln etwa 15- bis 20-mal pro Minute.',
  'Jeder Mensch hat einzigartige Fingerabdrücke – sogar eineiige Zwillinge.',
  'Zahnschmelz ist der härteste Stoff im menschlichen Körper.',
  'Der Körper eines Erwachsenen besteht zu etwa 60 % aus Wasser.',
  'Ein Mensch verbringt ungefähr ein Drittel seines Lebens mit Schlafen.',
  'Die Haut ist das größte Organ des Menschen.',
  'Alle Blutgefäße eines Menschen aneinandergelegt wären etwa 100.000 Kilometer lang – mehr als zweimal um die Erde.',
  'Haare wachsen ungefähr 1 Zentimeter pro Monat.',
  'Fingernägel wachsen schneller als Fußnägel.',

  // 🏛️ Geschichte & Erfindungen
  'Die Berliner Mauer fiel am 9. November 1989.',
  'Seit dem 3. Oktober 1990 ist Deutschland wiedervereinigt – deshalb feiern wir an diesem Tag den Tag der Deutschen Einheit.',
  'Die Pyramiden von Gizeh in Ägypten sind rund 4.500 Jahre alt.',
  'Die Cheops-Pyramide war fast 4.000 Jahre lang das höchste Bauwerk der Welt.',
  'Johannes Gutenberg erfand um 1450 in Mainz den Buchdruck mit beweglichen Buchstaben.',
  'Christoph Kolumbus erreichte 1492 Amerika.',
  'Carl Benz baute 1886 das erste Auto mit Benzinmotor.',
  'Bertha Benz machte 1888 die erste lange Autofahrt der Welt – rund 100 Kilometer von Mannheim nach Pforzheim.',
  'Die Brüder Wright machten 1903 den ersten Motorflug – er dauerte nur 12 Sekunden.',
  'Die ersten Olympischen Spiele der Neuzeit fanden 1896 in Athen statt.',
  'Die alten Römer hatten schon vor 2.000 Jahren Fußbodenheizungen.',
  'Albert Einstein wurde 1879 in Ulm geboren.',
  'Das Brandenburger Tor in Berlin wurde 1791 fertig gebaut.',
  'Der Kölner Dom ist 157 Meter hoch. Am Bau wurde über 600 Jahre lang gearbeitet.',
  'Der Eiffelturm in Paris wurde 1889 gebaut und ist rund 330 Meter hoch.',
  'Im Sommer ist der Eiffelturm ein paar Zentimeter höher als im Winter, weil sich Metall bei Wärme ausdehnt.',
  'Das höchste Gebäude der Welt ist der Burj Khalifa in Dubai – 828 Meter hoch.',
  'Die Chinesische Mauer ist mit allen Abschnitten über 21.000 Kilometer lang.',
  'Die Chinesische Mauer kann man vom Weltall aus NICHT mit bloßem Auge sehen – das ist ein Mythos.',
  'Der Euro wurde 2002 als Bargeld eingeführt.',
  'Das erste iPhone kam 2007 auf den Markt.',
  'Gummibärchen wurden 1922 in Bonn erfunden. Haribo steht für HAns RIegel BOnn.',
  'LEGO kommt aus Dänemark. Der Name kommt von „leg godt“ – das heißt „spiel gut“.',
  'Die Mona Lisa hängt im Louvre in Paris – und sie hat keine Augenbrauen.',
  'Die Märchen „Hänsel und Gretel“ und „Rotkäppchen“ wurden von den Brüdern Grimm gesammelt und aufgeschrieben.',
  'Schach wurde vermutlich vor rund 1.500 Jahren in Indien erfunden.',

  // 🍎 Essen
  'Honig wird nie schlecht – in ägyptischen Gräbern fand man Honig, der Tausende Jahre alt war.',
  'Bananen sind botanisch gesehen Beeren – Erdbeeren dagegen nicht.',
  'Tomaten sind botanisch gesehen Früchte.',
  'Erdnüsse sind gar keine Nüsse, sondern Hülsenfrüchte – wie Erbsen und Bohnen.',
  'Karotten waren früher meistens lila. Orange Karotten wurden erst vor rund 400 Jahren in den Niederlanden gezüchtet.',
  'In Deutschland gibt es über 3.000 verschiedene Brotsorten.',

  // ⚽ Sport, Sprache & Zahlen
  'Ein Marathon ist genau 42,195 Kilometer lang.',
  'Ein Fußballspiel dauert 90 Minuten – zwei Halbzeiten mit je 45 Minuten.',
  'Die fünf Olympischen Ringe stehen für die Kontinente, die bei den Spielen mitmachen.',
  'Auf der Welt werden über 7.000 verschiedene Sprachen gesprochen.',
  'Chinesisch (Mandarin) hat die meisten Muttersprachler der Welt.',
  'Das deutsche Alphabet hat 26 Buchstaben – dazu kommen noch ä, ö, ü und ß.',
  'Der häufigste Buchstabe in der deutschen Sprache ist das E.',
  'Ein Tag hat 86.400 Sekunden.',
  'Ein Jahr hat 52 Wochen und einen Tag – im Schaltjahr sogar zwei Tage.',
  'Fast alle vier Jahre gibt es ein Schaltjahr mit einem 29. Februar.',
];
